version: "3"
services:
  frontend-admin:
    build:
      context: "."
      target: "dev"
    container_name: "Admin"
    restart: "unless-stopped"
    working_dir: "/usr/src/nuxt-app"
    environment:
      - "APP_HOST=frontend-admin"
      - "APP_PORT=3000"
    ports:
      - "3000:3000"
    volumes:
      - "./assets:/usr/src/nuxt-app/assets"
      - "./components:/usr/src/nuxt-app/components"
      - "./layouts:/usr/src/nuxt-app/layouts"
      - "./middleware:/usr/src/nuxt-app/middleware"
      - "./pages:/usr/src/nuxt-app/pages"
      - "./plugins:/usr/src/nuxt-app/plugins"
      - "./server:/usr/src/nuxt-app/server"
      - "./store:/usr/src/nuxt-app/store"
      - "./static:/usr/src/nuxt-app/static"
      - "./m.js:/usr/src/nuxt-app/m.js"
      - "./nuxt.config.js:/usr/src/nuxt-app/nuxt.config.js"
  frontend-public:
    build:
      context: "."
      target: "production"
    container_name: "Public"
    restart: "unless-stopped"
    working_dir: "/usr/src/nuxt-app"
    environment:
      - "APP_HOST=frontend-public"
      - "APP_PORT=3001"
      - "APP_NAME=sample.com"
    ports:
      - "3001:3001"
    volumes:
      - "./assets:/usr/src/nuxt-app/assets"
      - "./components:/usr/src/nuxt-app/components"
      - "./layouts:/usr/src/nuxt-app/layouts"
      - "./middleware:/usr/src/nuxt-app/middleware"
      - "./pages:/usr/src/nuxt-app/pages"
      - "./plugins:/usr/src/nuxt-app/plugins"
      - "./server:/usr/src/nuxt-app/server"
      - "./store:/usr/src/nuxt-app/store"
      - "./static:/usr/src/nuxt-app/static"
      - "./m.js:/usr/src/nuxt-app/m.js"
      - "./nuxt.config.js:/usr/src/nuxt-app/nuxt.config.js"