version: "3"
services:
  backend:
    build:
      context: "../backend"
      args:
        BACKEND_PORT: 8000
    container_name: "BackEnd"
    restart: "unless-stopped"
    working_dir: "/usr/src/backend"
    environment:
      - "HOST=backend"
      - "ADMIN_SERVER_PORT=8000"
      - "PUBLIC_SERVER_PORT=9000"
      - "API_URL=aar_pmvkj"
      - "JWT_SECRET=sample_jwt_secret_you_should_change_this"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=ffmg_webpod"
      - "PGHOST=postgres"
      - "TABLE_PREFIX=czdo_"
    volumes:
      - "../backend:/usr/src/backend"
    depends_on:
      - "postgres"
      - "frontend-admin"
      - "frontend-public"
  frontend-admin:
    build:
      context: "../frontend-admin"
      target: "dev"
    container_name: "Admin"
    restart: "unless-stopped"
    working_dir: "/usr/src/admin"
    environment:
      - "APP_HOST=frontend-admin"
      - "APP_PORT=5000"
      - "ADMIN_ROUTE=wpadmin"
      - "API_URL=aar_pmvkj"
      - "API_BASE=backend:8000"
    volumes:
      - "../frontend-admin/assets:/usr/src/admin/assets"
      - "../frontend-admin/components:/usr/src/admin/components"
      - "../frontend-admin/layouts:/usr/src/admin/layouts"
      - "../frontend-admin/middleware:/usr/src/admin/middleware"
      - "../frontend-admin/pages:/usr/src/admin/pages"
      - "../frontend-admin/plugins:/usr/src/admin/plugins"
      - "../frontend-admin/server:/usr/src/admin/server"
      - "../frontend-admin/store:/usr/src/admin/store"
      - "../frontend-admin/static:/usr/src/admin/static"
      - "../frontend-admin/m.js:/usr/src/admin/m.js"
      - "../frontend-admin/undo-redo.js:/usr/src/admin/undo-redo.js"
      - "../frontend-admin/EventEmitter.js:/usr/src/admin/EventEmitter.js"
      - "../frontend-admin/nuxt.config.js:/usr/src/admin/nuxt.config.js"
  frontend-public:
    build:
      context: "../frontend-public"
      target: "dev"
    container_name: "Public"
    restart: "unless-stopped"
    working_dir: "/usr/src/public"
    environment:
      - "APP_HOST=frontend-public"
      - "APP_PORT=3000"
      - "APP_NAME=sample.com"
      - "API_URL=par_ypcdg"
    volumes:
      - "../frontend-public/assets:/usr/src/public/assets"
      - "../frontend-public/layouts:/usr/src/public/layouts"
      - "../frontend-public/middleware:/usr/src/public/middleware"
      - "../frontend-public/pages:/usr/src/public/pages"
      - "../frontend-public/plugins:/usr/src/public/plugins"
      - "../frontend-public/server:/usr/src/public/server"
      - "../frontend-public/components:/usr/src/public/components"
      - "../frontend-public/store:/usr/src/public/store"
      - "../frontend-public/static:/usr/src/public/static"
      - "../frontend-public/m.js:/usr/src/public/m.js"
      - "../frontend-public/nuxt.config.js:/usr/src/public/nuxt.config.js"
  nginx:
    image: "nginx:stable-alpine-perl"
    depends_on:
      - "backend"
      - "frontend-admin"
      - "frontend-public"
    container_name: "nginx"
    volumes:
      - "./nginx:/etc/nginx/templates"
      - "./nginx/certs:/etc/nginx/certs"
    ports:
      - "8443:8443"
      - "80:80"
    environment:
      - "NGINX_HTTPS_PORT=8443"
      - "NGINX_HOST=localhost"
      - "NGINX_PORT=80"
      - "PUBLIC_FRONTEND_SERVER_UPSTREAM=frontend-public:3000"
      - "PUBLIC_BACKEND_UPSTREAM=backend:9000"
      - "PUBLIC_API_LINK=par_ypcdg"
      - "ADMIN_FRONTEND_SERVER_UPSTREAM=frontend-admin:5000"
      - "ADMIN_DASHBOARD_PUBLIC_LINK=wpadmin"
      - "ADMIN_BACKEND_SERVER=backend:8000"
      - "ADMIN_EXPRESS_ROUTE=aar_pmvkj"
      - "PGADMIN_URL=pgadmin"
  postgres:
    container_name: "postgres"
    image: "postgres"
    restart: "always"
    ports:
      - "5432"
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=ffmg_webpod"
      - "PGHOST=postgres"
      - "TABLE_PREFIX=czdo_"
    volumes:
      - "../postgres:/var/lib/postgresql/data"
  pgadmin:
    container_name: "pgadmin"
    image: "dpage/pgadmin4"
    restart: "unless-stopped"
    ports:
      - "5555:80"
    environment:
      - "PGADMIN_DEFAULT_EMAIL=user@domain.com"
      - "PGADMIN_DEFAULT_PASSWORD=password"
      - "PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True"
      - "PGADMIN_CONFIG_LOGIN_BANNER=\"Webpod authorized users only!\""
    volumes:
      - "../pgadmin:/var/lib/pgadmin"
      - "../pgadmin:/pgadmin4/servers.json"
      - "../pgadmin:/pgadmin4/config_local.py"
