version: "3"
services:
  backend:
    build:
      context: "../backend"
    container_name: "BackEnd"
    restart: "unless-stopped"
    working_dir: "/usr/src/backend"
    environment:
      - "HOST=backend"
      - "PORT=8000"
    ports:
      - "8000:8000"
    depends_on:
      - "frontend-admin"
      - "frontend-public"
    networks:
      - "backend-network"
  frontend-admin:
    build:
      context: "../frontend-admin"
      target: "dev"
    container_name: "Admin"
    restart: "unless-stopped"
    working_dir: "/usr/src/admin"
    environment:
      - "APP_HOST=frontend-admin"
      - "APP_PORT=5000"
      - "ADMIN_ROUTE=wpadmin"
    networks:
      - "admin-network"
    ports:
      - "5000:5000"
    volumes:
      - "../frontend-admin/assets:/usr/src/admin/assets"
      - "../frontend-admin/components:/usr/src/admin/components"
      - "../frontend-admin/layouts:/usr/src/admin/layouts"
      - "../frontend-admin/middleware:/usr/src/admin/middleware"
      - "../frontend-admin/pages:/usr/src/admin/pages"
      - "../frontend-admin/plugins:/usr/src/admin/plugins"
      - "../frontend-admin/server:/usr/src/admin/server"
      - "../frontend-admin/store:/usr/src/admin/store"
      - "../frontend-admin/static:/usr/src/admin/static"
      - "../frontend-admin/m.js:/usr/src/admin/m.js"
      - "../frontend-admin/nuxt.config.js:/usr/src/admin/nuxt.config.js"
  frontend-public:
    build:
      context: "../frontend-public"
      target: "production"
    container_name: "Public"
    restart: "unless-stopped"
    working_dir: "/usr/src/nuxt"
    environment:
      - "APP_HOST=frontend-public"
      - "APP_PORT=3000"
      - "APP_NAME=sample.com"
    ports:
      - "3000:3000"
    networks:
      - "public-network"
    volumes:
      - "../frontend-public/assets:/usr/src/public/assets"
      - "../frontend-public/layouts:/usr/src/public/layouts"
      - "../frontend-public/middleware:/usr/src/public/middleware"
      - "../frontend-public/pages:/usr/src/public/pages"
      - "../frontend-public/plugins:/usr/src/public/plugins"
      - "../frontend-public/server:/usr/src/public/server"
      - "../frontend-public/store:/usr/src/public/store"
      - "../frontend-public/static:/usr/src/public/static"
      - "../frontend-public/m.js:/usr/src/public/m.js"
      - "../frontend-public/nuxt.config.js:/usr/src/public/nuxt.config.js"
  nginx:
    image: "nginx"
    depends_on:
      - "backend"
      - "frontend-admin"
      - "frontend-public"
    container_name: "nginx"
    volumes:
      - "./nginx:/etc/nginx/templates"
      - "./nginx/certs:/etc/nginx/certs"
    ports:
      - "8443:8443"
      - "80:80"
    environment:
      - "NGINX_HTTPS_PORT=8443"
      - "NGINX_HOST=localhost"
      - "NGINX_PORT=80"
      - "UPSTREAM_ADMIN=frontend-admin:5000"
      - "ADMIN_ROUTE=wpadmin"
      - "UPSTREAM_PUBLIC=frontend-public:3000"
      - "BACKEND_ROUTE=iasdhflasihsdfpq"
      - "UPSTREAM_BACKEND=backend:8000"
      - "PGADMIN_URL=mydb"
    networks:
      - "backend-network"
      - "admin-network"
      - "public-network"
networks:
  admin-network:
    driver: "bridge"
  public-network:
    driver: "bridge"
  backend-network:
    driver: "bridge"
